---
# file: roles/common/tasks/main.yml

- name: Remove some packages
  apt: name={{ item }} state=absent 
  tags: packages
  with_items:
    - docker.io
    - python-flask
    - python-gtk2
    - python-ipaddress
    - python-jinja2
    - python-markupsafe
    - ubuntu-fan

- name: Install some packages
  apt: name={{ item }} state=present install_recommends=no
  tags: packages
  with_items:
    - parallel
    - wireless-tools
    - wpasupplicant
    - jq
    - htop
    - dstat
    - tmux
    - unzip
    - wget
    - git
    - vim
    - python-virtualenv
    - python-dbus
    - python
    - python-smbus
    - python-pip
    - python-pil
    - python-pyexiv2
    - python-smbus
  ignore_errors: True

- name: Install some pip packages
  pip: name={{ item.name }} state={{ item.state }}
  with_items:
    - { name: wireless, state: absent }
    - { name: ipython, state: absent }
    - { name: ipdb, state: absent }
    - { name: wifi, state: absent }
    - { name: uWSGI, state: absent }

  ignore_errors: True

- name: Create /home/venvs
  file: path=/home/venvs state=directory

- name: Copy file to disable sleep on wifi interface
  copy: src=files/8192cu.conf dest=/etc/modprobe.d/8192cu.conf

- name: Manually create the initial virtualenv
  command: virtualenv /home/venvs/piricohmoto -p /usr/bin/python2 creates="/home/venvs/piricohmoto" --system-site-packages

- name: Be sure certain folders are present
  file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state=directory recurse=true
  with_items:
    - { path: '/download', owner: 'root', group: 'root', mode: '0600' }
    - { path: '/config', owner: 'root', group: 'root', mode: '0755' }
    - { path: "{{ install_root }}", owner: 'root', group: 'root', mode: '0755' }

- name: Copy a base interfaces file that has a static IP
  template: src=templates/interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644 backup=yes
  notify:
    - restart networking

- name: Copy a hostname file
  template: src=templates/hostname.j2 dest=/etc/hostname owner=root group=root mode=0644 backup=yes

- name: Copy a hosts file
  template: src=templates/hosts.j2 dest=/etc/hosts owner=root group=root mode=0644 backup=yes

- name: Copy a base 10-network.rules file
  template: src=templates/10-network.rules.j2 dest=/etc/udev/rules.d/10-network.rules owner=root group=root mode=0644 backup=yes

- name: Copy a base wpa_supplicant file
  template: src=templates/wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf owner=root group=root mode=0644 backup=yes
  notify:
    - restart networking
  tags: networking

- name: Ensure USB storage is configured
  mount: name=/download src=/dev/sda1 fstype=vfat opts=auto,users,rw,uid=1001,gid=1001,umask=0002,nofail state=present

- name: Copy network light indicator script to the network interfaces scripts directory
  template: src=templates/network-light.sh.j2 dest={{ install_root }}/bin//network-light.sh owner=root group=root mode=0755
