---

#- name: Initialise a bare repo in /home/ubuntu

- name: Create bare repo dir
  file: path=/home/ubuntu/piricohmoto.git owner=ubuntu group=ubuntu mode=0775 state=directory
  tags: git

- name: Initialise a bare repo in home dir
  command: chdir=/home/ubuntu/piricohmoto.git creates=/home/ubuntu/piricohmoto.git/HEAD git init --bare
  tags: git

- name: ensure repositories permisions
  file: path=/home/ubuntu/piricohmoto.git owner=ubuntu group=ubuntu recurse=True
  tags: postreceive

- name: Copy post receive hook
  template: src=templates/post-receive.j2 dest=/home/ubuntu/piricohmoto.git/hooks/post-receive owner=ubuntu group=ubuntu mode=0755

- name: Ensure packages are installed
  apt: name={{ item }} state=installed
  tags: packages
  with_items:
    - python-pil
    - python-pip
    - python-pyexiv2
    - python-gps
    - python-smbus
    - gpsd
    - gpsd-clients 
    - nginx
    - redis-server
  ignore_errors: True

- name: Check out piricohmoto project into /code folder
  git: repo=/home/ubuntu/piricohmoto.git
       dest={{ install_root }}
       version=devel update=yes
  ignore_errors: True


- name: Ensure appuser exists
  user: name=appuser shell=/bin/bash groups=i2c

- name: Copy sudoers.d file
  copy: src=files/appuser.sudo dest=/etc/sudoers.d/appuser 

- name: Install some pip packages
  pip: name={{ item }} state=latest virtualenv=/home/venvs/piricohmoto extra_args="--timeout=5"
  with_items:
    - redis
    - PyYaml
    - flask
    - flask_bootstrap
    - uWSGI
    - piglow
    - requests
    - dropbox
    - sh
    - ipython
    - ipdb
    - uWSGI
  ignore_errors: True

- name: Ensure systemd file for supervisor is installed
  copy: src=/lib/systemd/system/supervisor.service dest=/etc/systemd/system/supervisor.service remote_src=True

- name: Copy supervisor files
  template: src={{ item }}.j2 dest=/etc/supervisor/conf.d/{{ item }}.conf
  with_items:
    - piricohmotoServiceLogger
    - piricohmotoServiceNotifier
    - piricohmotoCheckinternet
    - piricohmotoServiceMain
  notify:
    - restart supervisor
  tags: supervisor

#- name: Remove supervisor files
#  file: path=/etc/supervisor/conf.d/{{ item }}.conf state=absent
#  with_items:
#    - piricohmotoServiceMain
#  notify:
#    - restart supervisor
#  tags: supervisor

- name: Create nginx SSL dir
  file: path=/etc/nginx/ssl state=directory owner=root group=root mode=0600

- name: Copy over SSL PEM certificate
  template: src=templates/piricohmoto.pem.j2 dest=/etc/nginx/ssl/piricohmoto.pem owner=root group=root mode=0600
  notify: restart nginx

- name: Create uWSGI log dir
  file: path=/var/log/uwsgi state=directory owner=www-data group=www-data

- name: Copy over nginx base config
  copy: src=files/piricohmoto.conf dest=/etc/nginx/sites-available/piricohmoto owner=root group=root mode=0600
  notify: restart nginx

- name: Ensure my piricohmoto folder exists
  file: path=/var/www/piricohmoto state=directory owner=root group=root mode=0755

- name: Be sure certain folders are present
  file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state=directory
  with_items:
    - { path: '/etc/uwsgi', owner: 'root', group: 'root', mode: '0755' }
    - { path: '/etc/uwsgi/vassals', owner: 'root', group: 'root', mode: '0755' }
    - { path: '/var/log/piricohmoto', owner: 'appuser', group: 'root', mode: '0755' }
    - { path: '/download', owner: 'appuser', group: 'appuser', mode: '0755' }

- name: Copy over uWSGI config
  template: src=templates/piricohmoto.uwsgi.ini.j2 dest=/var/www/piricohmoto/piricohmoto_uwsgi.ini owner=root group=root mode=0644
  notify: restart nginx

- name: Link config in vassals folder
  file: dest=/etc/uwsgi/vassals/piricohmoto_uwsgi.ini src=/var/www/piricohmoto/piricohmoto_uwsgi.ini state=link 

- name: Copy over the uwsgi.init systemd job
  copy: src=files/uwsgi.service dest=/etc/systemd/system/uwsgi.service owner=root group=root mode=0644
  notify:
   - reload systemctl
   - restart uwsgi

- name: Link nginx base config
  file: src=/etc/nginx/sites-available/piricohmoto dest=/etc/nginx/sites-enabled/piricohmoto state=link
  notify: restart nginx

- name: Remove nginx default config
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: Give ownership of all files in folder to www-data
  file: path="{{ item }}" owner=www-data group=www-data recurse=true
  with_items:
    - "{{ install_root }}/config_app"
    - /var/www/piricohmoto

- name: Create a symlink for the config_app
  file: src={{ install_root }}/config_app dest=/var/www/piricohmoto/config_app state=link

- name: Copy over piricohmoto config `
  template: src=templates/piricohmoto.yml.j2 dest=/config/piricohmoto.yml owner=appuser group=appuser mode=0600

- name: Ensure services are running
  service: name="{{ item }}" state=running enabled=yes
  tags: services
  with_items: 
    - gpsd
    - redis-server
    - supervisor
    - nginx
    - uwsgi


