---

#- name: Initialise a bare repo in /home/ubuntu

- name: Ensure packages are installed
  apt: name={{ item }} state=installed
  tags: packages
  with_items:
    - nginx
  ignore_errors: True

- name: Check out Bootstrap-Image-Gallery project into /opt folder
  git: repo=https://github.com/blueimp/Bootstrap-Image-Gallery dest=/opt/Bootstrap-Image-Gallery update=yes
  ignore_errors: True

- name: Ensure appuser exists
  user: name=appuser shell=/bin/bash groups=i2c

- name: Copy sudoers.d file
  copy: src=files/appuser.sudo dest=/etc/sudoers.d/appuser
  tags: sudo 

- name: Create nginx SSL dir
  file: path=/etc/nginx/ssl state=directory owner=root group=root mode=0600

- name: Copy over SSL PEM certificate
  template: src=templates/piricohmoto.pem.j2 dest=/etc/nginx/ssl/piricohmoto.pem owner=root group=root mode=0600
  notify: restart nginx

- name: Create uWSGI log dir
  file: path=/var/log/uwsgi state=directory owner=www-data group=www-data

- name: Copy over nginx base config
  copy: src=files/piricohmoto.conf dest=/etc/nginx/sites-available/piricohmoto owner=root group=root mode=0600
  notify: restart nginx

- name: Copy over uWSGI config
  template: src=templates/piricohmoto.uwsgi.ini.j2 dest=/var/www/piricohmoto/piricohmoto_uwsgi.ini owner=root group=root mode=0644
  notify: restart nginx

- name: Link config in vassals folder
  file: dest=/etc/uwsgi/vassals/piricohmoto_uwsgi.ini src=/var/www/piricohmoto/piricohmoto_uwsgi.ini state=link 

- name: Copy over the uwsgi.init systemd job
  copy: src=files/uwsgi.service dest=/etc/systemd/system/uwsgi.service owner=root group=root mode=0644
  notify:
   - reload systemctl
   - restart uwsgi

- name: Link nginx base config
  file: src=/etc/nginx/sites-available/piricohmoto dest=/etc/nginx/sites-enabled/piricohmoto state=link
  notify: restart nginx

- name: Remove nginx default config
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: Ensure services are running
  service: name="{{ item }}" state=running enabled=yes
  tags: services
  with_items: 
    - nginx
    - uwsgi

